backend:
  name: git-gateway
  branch: master

media_folder: images/uploads
public_folder: images/uploads

collections:
  - name: "TheElms"
    label: "The Elms"
    folder: "src/markdown-pages/TheElms"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
