backend:
  name: git-gateway
  branch: master

media_folder: src/images/uploads
public_folder: src/images/uploads

collections:
  - name: "cottage-details"
    label: "Cottage Details"
    folder: "src/markdown-pages/cottage-details"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Exterior Image", name: "ExteriorImage", widget: "image" }
