backend:
  name: git-gateway
  branch: master

media_folder: src/images/uploads
public_folder: src/images/uploads

collections:
  - name: "cottage-details"
    label: "Cottage Details"
    folder: "src/markdown-pages/cottage-details"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Sample Pics",
          name: "samplePics",
          widget: "list",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              {
                label: "Image Description",
                name: "imageAlt",
                widget: "string",
              },
              { label: "Image", name: "image", widget: "image" },
              {
                label: "Image Description",
                name: "imageAlt",
                widget: "string",
              },
            ],
        }
